# Generated by Django 2.1.4 on 2018-12-06 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amalproducts', '0003_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
