# Generated by Django 2.1.4 on 2018-12-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amalproducts', '0005_auto_20181207_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
